services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ruvents\RuworkBundle\Doctrine\NamingStrategy\RuworkNamingStrategy: ~

  Ruvents\RuworkBundle\EventListener\RedirectControllerListener: ~

  Ruvents\RuworkBundle\ExpressionLanguage\UrlExpressionLanguage: ~

  Ruvents\RuworkBundle\Mailer\Mailer:
    public: true

  Ruvents\RuworkBundle\Monolog\Processor\RequestProcessor:
    tags:
      - { name: monolog.processor, method: processRecord, channel: request }

  Ruvents\RuworkBundle\Security\AuthenticationHelper:
    public: true

  Ruvents\RuworkBundle\Serializer\Encoder\ExcelCsvEncoder: ~

  Ruvents\RuworkBundle\Validator\Constraints\AliasValidator: ~
