services:
  ruwork.mailer:
    class: Ruwork\CoreBundle\Mailer\Mailer
    arguments:
      - '@mailer'
      - '@twig'

  ruwork.monolog.processor.request:
    class: Ruwork\CoreBundle\Monolog\Processor\RequestProcessor
    public: false
    arguments:
      - '@request_stack'
    tags:
      - { name: monolog.processor, method: processRecord, channel: request }
