services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ruwork\CoreBundle\Doctrine\NamingStrategy\RuworkNamingStrategy: ~

  Ruwork\CoreBundle\Mailer\Mailer:
    public: true

  Ruwork\CoreBundle\Monolog\Processor\RequestProcessor:
    tags:
      - { name: monolog.processor, method: processRecord, channel: request }

  Ruwork\CoreBundle\Security\AuthenticationHelper:
    public: true

  Ruwork\CoreBundle\Serializer\Encoder\ExcelCsvEncoder: ~

  Ruwork\CoreBundle\Validator\Constraints\AliasValidator: ~
