services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ruwork\CoreBundle\Doctrine\RuworkNamingStrategy: ~

  Ruwork\CoreBundle\Mailer\Mailer:
    public: true

  Ruwork\CoreBundle\Monolog\Processor\RequestProcessor:
    tags:
      - { name: monolog.processor, method: processRecord, channel: request }

  Ruwork\CoreBundle\Security\AuthenticationHelper:
    public: true

  Ruwork\CoreBundle\Serializer\Encoder\ExcelCsvEncoder: ~

  Ruwork\CoreBundle\Validator\Constraints\AliasValidator: ~

  # Twig Extensions
  Twig\Extensions\ArrayExtension: ~
  Twig\Extensions\DateExtension: ~
  Twig\Extensions\IntlExtension: ~
  Twig\Extensions\TextExtension: ~

  # Ruvents Twig Extensions
  Ruvents\TwigExtensions\ClassExtension: ~
  Ruvents\TwigExtensions\SortByExtension: ~
  Ruvents\TwigExtensions\SortExtension: ~
  Ruvents\TwigExtensions\InflectorExtension: ~
  Ruvents\TwigExtensions\StringExtension: ~
  Ruvents\TwigExtensions\FileExtension: ~
  Ruvents\TwigExtensions\MarkdownExtension: ~
  Ruvents\TwigExtensions\IntlDateExtension: ~
