services:
  ruwork.mailer.message_factory:
    class: Ruwork\CoreBundle\Mailer\MessageFactory
    arguments:
      - '@twig'
      - '@?translator'
      - ~

  ruwork.monolog.processor.request:
    class: Ruwork\CoreBundle\Monolog\Processor\RequestProcessor
    public: false
    arguments:
      - '@request_stack'
    tags:
      - { name: monolog.processor, method: processRecord, channel: request }
