services:
  ruwork.mailer.message_factory:
    class: Ruwork\CoreBundle\Mailer\MessageFactory
    arguments:
      - '@twig'
      - '@?translator'
      - ~

  ruwork.monolog.processor.request:
    class: Ruwork\CoreBundle\Monolog\Processor\RequestProcessor
    public: false
    arguments:
      - '@request_stack'
    tags:
      - { name: monolog.processor, method: processRecord, channel: request }

  ruwork.security.auth_helper:
    class: Ruwork\CoreBundle\Security\AuthenticationHelper
    arguments:
      - '@security.token_storage'
      - '@security.user_checker'
      - '@security.authentication.session_strategy'
      - '@request_stack'
      - ~

  ruwork.serializer.encoder.excel_csv:
    class: Ruwork\CoreBundle\Serializer\Encoder\ExcelCsvEncoder
    public: false
    tags:
      - { name: serializer.encoder }
